

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    depends_on:
      - postgres
    ports:
      - "9966:9966"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
