name: Merge Build

on:
  push:
    branches:
      - develop

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: |
          docker build -t petclinic-frontend:latest .

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t petclinic-backend:latest .

      - name: Build Postgres Docker Image
        working-directory: ./postgres
        run: |
          docker build -t petclinic-postgres:latest .
